C#/MVCEF3Capas/Presentacion/Controllers/AlumnosController.cs
using Entidades;
using Negocio;
using Negocio.WCFAlumno;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Presentacion.Controllers
{
    public class AlumnosController : Controller
    {
        NAlumno _nAlumno = new NAlumno();
        NEstado _estado = new NEstado();
        NEstatus _estatus = new NEstatus();
        ItemTablaISR _tablaISR = new ItemTablaISR();
        AportacionesIMSS _alumnoIMSS = new AportacionesIMSS();
        

        // GET: Alumnos
        public ActionResult Index()
        {
            return View(_nAlumno.Consultar());
        }

        // GET: Alumnos/Details/5
        public ActionResult Details(int id)
        {
            return View(_nAlumno.Consultar(id));
        }

        // GET: Alumnos/Create
        public ActionResult Create()
        {
            ViewBag.listEstados = _estado.Consultar();
            ViewBag.listEstatus = _estatus.Consultar();
            return View();
        }

        // POST: Alumnos/Create
        [HttpPost]
        public ActionResult Create(Alumnos alumno)
        {
            try
            {
                _nAlumno.Agregar(alumno);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Alumnos/Edit/5
        public ActionResult Edit(int id)
        {
            ViewBag.listEstados = _estado.Consultar();
            ViewBag.listEstatus = _estatus.Consultar();
            return View(_nAlumno.Consultar(id));
        }

        // POST: Alumnos/Edit/5
        [HttpPost]
        public ActionResult Edit(Alumnos alumno)
        {
            try
            {
                _nAlumno.Actualizar(alumno);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Alumnos/Delete/5
        public ActionResult Delete(int id)
        {
            return View(_nAlumno.Consultar(id));
        }

        // POST: Alumnos/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                _nAlumno.Eliminar(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult _AportacionesIMSS(int id)
        {
            _alumnoIMSS = _nAlumno.CalcularIMSS(id);
            return PartialView(_alumnoIMSS);
        }

        public ActionResult _TablaISR(int id)
        {
            _tablaISR = _nAlumno.CalcularISR(id);
            return PartialView(_tablaISR);

        }

    }
}

C#/MVCEF3Capas/Presentacion/Controllers/EstatusAlumnosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Entidades;
using Negocio;

namespace Presentacion.Controllers
{
    public class EstatusAlumnosController : Controller
    {
        NEstatus _estatus = new NEstatus();
        // GET: EstatusAlumnos
        public ActionResult Index()
        {
            return View(_estatus.Consultar());
        }

        // GET: EstatusAlumnos/Details/5
        public ActionResult Details(int id)
        {
            return View(_estatus.Consultar(id));
        }

        // GET: EstatusAlumnos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EstatusAlumnos/Create
        [HttpPost]
        public ActionResult Create(EstatusAlumnos estatusAlumnos)
        {
            try
            {
                _estatus.Agregar(estatusAlumnos); 
            }
            catch
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        // GET: EstatusAlumnos/Edit/5
        public ActionResult Edit(int id)
        {
            return View(_estatus.Consultar(id)); 
        }

        // POST: EstatusAlumnos/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, EstatusAlumnos estatusAlumnos)
        {
            try
            {
                _estatus.Actualizar(estatusAlumnos);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: EstatusAlumnos/Delete/5
        public ActionResult Delete(int id)
        {
            return View(_estatus.Consultar(id));
        }

        // POST: EstatusAlumnos/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, EstatusAlumnos estatusAlumnos)
        {
            try
            {
                _estatus.Eliminar(id);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

C#/MVCEF3Capas/Presentacion/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Presentacion.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

C#/MVCEF3Capas/Presentacion/Views/Alumnos/Create.cshtml
@model Entidades.Alumnos

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Crear</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <form class="form-horizontal">
        <h4>Alumnos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group row" style="text-align:right">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-sm-2", @style = "padding-top:5px" })
            <div class="col-sm-10" style="text-align:left">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />

        <div class="form-group row" style="text-align:right">
            @Html.LabelFor(model => model.primerApellido, htmlAttributes: new { @class = "control-label col-sm-2", @style = "padding-top:5px" })
            <div class="col-sm-10" style="text-align:left">
                @Html.EditorFor(model => model.primerApellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.primerApellido, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />

        <div class="form-group row" style="text-align:right">
            @Html.LabelFor(model => model.segundoApellido, htmlAttributes: new { @class = "control-label col-sm-2", @style = "padding-top:5px" })
            <div class="col-sm-10" style="text-align:left">
                @Html.EditorFor(model => model.segundoApellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.segundoApellido, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />

        <div class="form-group row" style="text-align:right">
            @Html.LabelFor(model => model.correo, htmlAttributes: new { @class = "control-label col-sm-2", @style = "padding-top:5px" })
            <div class="col-sm-10" style="text-align:left">
                @Html.EditorFor(model => model.correo, new { htmlAttributes = new { @class = "form-control", type = "email" } })
                @Html.ValidationMessageFor(model => model.correo, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />

        <div class="form-group row" style="text-align:right">
            @Html.LabelFor(model => model.telefono, htmlAttributes: new { @class = "control-label col-sm-2", @style = "padding-top:5px" })
            <div class="col-sm-10" style="text-align:left">
                @Html.EditorFor(model => model.telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.telefono, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />

        <div class="form-group row" style="text-align:right">
            @Html.LabelFor(model => model.fechaNacimiento, htmlAttributes: new { @class = "control-label col-sm-2", @style = "padding-top:5px" })
            <div class="col-sm-10" style="text-align:left">
                @Html.EditorFor(model => model.fechaNacimiento, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                @Html.ValidationMessageFor(model => model.fechaNacimiento, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />

        <div class="form-group row" style="text-align:right">
            @Html.LabelFor(model => model.curp, htmlAttributes: new { @class = "control-label col-sm-2", @style = "padding-top:5px" })
            <div class="col-sm-10" style="text-align:left">
                @Html.EditorFor(model => model.curp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.curp, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />

        <div class="form-group row" style="text-align:right">
            @Html.LabelFor(model => model.sueldo, htmlAttributes: new { @class = "control-label col-sm-2", @style = "padding-top:5px" })
            <div class="col-sm-10" style="text-align:left">
                @Html.EditorFor(model => model.sueldo, new { htmlAttributes = new { @class = "form-control", type = "number" } })
                @Html.ValidationMessageFor(model => model.sueldo, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />

        <div class="form-group row" style="text-align:right">
            @Html.LabelFor(model => model.idEstadoOrigen, htmlAttributes: new { @class = "control-label col-sm-2", @style = "padding-top:5px" })
            <div class="col-sm-10" style="text-align:left">
                @Html.DropDownList("idEstadoOrigen", new SelectList(ViewBag.listEstados, "id", "nombre"), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idEstadoOrigen, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />

        <div class="form-group row" style="text-align:right">
            @Html.LabelFor(model => model.idEstatus, htmlAttributes: new { @class = "control-label col-sm-2", @style = "padding-top:5px" })
            <div class="col-sm-10" style="text-align:left">
                @Html.DropDownList("idEstatus", new SelectList(ViewBag.listEstatus, "id", "nombre"), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idEstatus, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-2" style="text-align:right">
                <input type="submit" value="Agregar" class="btn btn-success" />
            </div>
            <div class="col-auto">
                @Html.ActionLink("Regresar", "Index", null, new { @class = "btn btn-primary" })
            </div>

        </div>
    </form>

}




@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

C#/MVCEF3Capas/Presentacion/Views/Alumnos/Delete.cshtml
@model Entidades.Alumnos

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Eliminar</h2>
<h3>Estas seguro que deseas eliminar?</h3>
<br />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div>
        <h4>Alumnos</h4>
        <hr />
        <dl class="dl-horizontal">
            <div class="row">
                <dt class="col-2" style="text-align:right">
                    ID
                </dt>
                <dd class="col-auto">
                    @Html.DisplayFor(model => model.id)
                </dd>
            </div>

            <div class="row">
                <dt class="col-2" style="text-align:right">
                    Nombre
                </dt>
                <dd class="col-auto">
                    @Html.DisplayFor(model => model.nombre)
                </dd>
            </div>

            <div class="row">
                <dt class="col-2" style="text-align:right">
                    Primer Apellido
                </dt>
                <dd class="col-auto">
                    @Html.DisplayFor(model => model.primerApellido)
                </dd>
            </div>

            <div class="row">
                <dt class="col-2" style="text-align:right">
                    Segundo Apellido
                </dt>
                <dd class="col-auto">
                    @Html.DisplayFor(model => model.segundoApellido)
                </dd>
            </div>

            <div class="row">
                <dt class="col-2" style="text-align:right">
                    Fecha de Nacimiento
                </dt>
                <dd class="col-auto">
                    @Html.DisplayFor(model => model.fechaNacimiento).ToString().Substring(1, 10)
                </dd>
            </div>

            <div class="row">
                <dt class="col-2" style="text-align:right">
                    CURP
                </dt>
                <dd class="col-auto">
                    @Html.DisplayFor(model => model.curp)
                </dd>
            </div>

            <div class="row">
                <dt class="col-2" style="text-align:right">
                    Correo
                </dt>
                <dd class="col-auto">
                    @Html.DisplayFor(model => model.correo)
                </dd>
            </div>

            <div class="row">
                <dt class="col-2" style="text-align:right">
                    Telefono
                </dt>
                <dd class="col-auto">
                    @Html.DisplayFor(model => model.telefono)
                </dd>
            </div>

            <div class="row">
                <dt class="col-2" style="text-align:right">
                    Sueldo Mensual
                </dt>
                <dd class="col-auto">
                    @Html.DisplayFor(model => model.sueldo)
                </dd>
            </div>

            <div class="row">
                <dt class="col-2" style="text-align:right">
                    Estado
                </dt>
                <dd class="col-auto">
                    @Html.DisplayFor(model => model.Estados.nombre)
                </dd>
            </div>

            <div class="row">
                <dt class="col-2" style="text-align:right">
                    Estatus
                </dt>
                <dd class="col-auto">
                    @Html.DisplayFor(model => model.EstatusAlumnos.nombre)
                </dd>
            </div>

        </dl>

        <div class="row">
            <div class="col-2" style="text-align:right">
                <input type="submit" value="Eliminar" class="btn btn-danger" />

            </div>
            <div class="col-auto">
                @Html.ActionLink("Regresar", "Index", null, new { @class = "btn btn-primary" })
            </div>

        </div>

    </div>
}

C#/MVCEF3Capas/Presentacion/Views/Alumnos/Details.cshtml
@model Entidades.Alumnos

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalles</h2>
<br />
<div>
    <h4>Alumnos</h4>
    <hr />
    <dl class="dl-horizontal">
        <div class="row">
            <dt class="col-2" style="text-align:right">
                ID
            </dt>
            <dd class="col-auto">
                @Html.DisplayFor(model => model.id)
                <span id="idAlumno" hidden>@Html.DisplayFor(model => model.id)</span>
            </dd>
        </div>

        <div class="row">
            <dt class="col-2" style="text-align:right">
                Nombre
            </dt>
            <dd class="col-auto">
                @Html.DisplayFor(model => model.nombre)
            </dd>
        </div>

        <div class="row">
            <dt class="col-2" style="text-align:right">
                Primer Apellido
            </dt>
            <dd class="col-auto">
                @Html.DisplayFor(model => model.primerApellido)
            </dd>
        </div>

        <div class="row">
            <dt class="col-2" style="text-align:right">
                Segundo Apellido
            </dt>
            <dd class="col-auto">
                @Html.DisplayFor(model => model.segundoApellido)
            </dd>
        </div>

        <div class="row">
            <dt class="col-2" style="text-align:right">
                Fecha de Nacimiento
            </dt>
            <dd class="col-auto">
                @Html.DisplayFor(model => model.fechaNacimiento).ToString().Substring(1, 10)
            </dd>
        </div>

        <div class="row">
            <dt class="col-2" style="text-align:right">
                CURP
            </dt>
            <dd class="col-auto">
                @Html.DisplayFor(model => model.curp)
            </dd>
        </div>

        <div class="row">
            <dt class="col-2" style="text-align:right">
                Correo
            </dt>
            <dd class="col-auto">
                @Html.DisplayFor(model => model.correo)
            </dd>
        </div>

        <div class="row">
            <dt class="col-2" style="text-align:right">
                Telefono
            </dt>
            <dd class="col-auto">
                @Html.DisplayFor(model => model.telefono)
            </dd>
        </div>

        <div class="row">
            <dt class="col-2" style="text-align:right">
                Sueldo Mensual
            </dt>
            <dd class="col-auto">
                @Html.DisplayFor(model => model.sueldo)
            </dd>
        </div>

        <div class="row">
            <dt class="col-2" style="text-align:right">
                Estado
            </dt>
            <dd class="col-auto">
                @Html.DisplayFor(model => model.Estados.nombre)
            </dd>
        </div>

        <div class="row">
            <dt class="col-2" style="text-align:right">
                Estatus
            </dt>
            <dd class="col-auto">
                @Html.DisplayFor(model => model.EstatusAlumnos.nombre)
            </dd>
        </div>
    </dl>

    <div class="modal" id="ventanaModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Detalle Alumno</h5>
                    <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true" class="text-danger">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="modalPr"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
</div>
<div>
    <button class="btn btn-success" onclick="CalcularIMSS()">Calcular IMSS</button>
    <button class="btn btn-success" onclick="CalcularISR()">Calcular ISR</button>
    @Html.ActionLink("Regresar", "Index", null, new { @class = "btn btn-primary" })
</div>
<br />
<script type="text/javascript">

    function CalcularIMSS() {
        var id = $("#idAlumno").text();
        $(".modal-title").text("Calcular IMSS")
        var urlAction = "@Url.Action("_AportacionesIMSS", "Alumnos")" + "/" + id;
        LLamaAJAXGEThtml(urlAction, muestraModal);
    }
    function CalcularISR() {
        var id = $("#idAlumno").text();
        $(".modal-title").text("Calcular ISR")
        var urlAction = "@Url.Action("_TablaISR", "Alumnos")" + "/" + id;

        LLamaAJAXGEThtml(urlAction, muestraModal);
    }

    function muestraModal(response) {
        $("#modalPr").html(response)
        $("#ventanaModal").modal("show");
    }

@section Scripts {
    @Scripts.Render("~/bundles/mibundle")
}

</script>

C#/MVCEF3Capas/Presentacion/Views/Alumnos/Edit.cshtml
@model Entidades.Alumnos

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    <div class="form-horizontal">
        <h4>Alumnos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group row" style="text-align:right">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-sm-2", @style = "padding-top:5px" })
            <div class="col-sm-10" style="text-align:left">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />

        <div class="form-group row" style="text-align:right">
            @Html.LabelFor(model => model.primerApellido, htmlAttributes: new { @class = "control-label col-sm-2", @style = "padding-top:5px" })
            <div class="col-sm-10" style="text-align:left">
                @Html.EditorFor(model => model.primerApellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.primerApellido, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />

        <div class="form-group row" style="text-align:right">
            @Html.LabelFor(model => model.segundoApellido, htmlAttributes: new { @class = "control-label col-sm-2", @style = "padding-top:5px" })
            <div class="col-sm-10" style="text-align:left" >
                @Html.EditorFor(model => model.segundoApellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.segundoApellido, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />

        <div class="form-group row" style="text-align:right">
            @Html.LabelFor(model => model.correo, htmlAttributes: new { @class = "control-label col-sm-2", @style = "padding-top:5px" })
            <div class="col-sm-10" style="text-align:left">
                @Html.EditorFor(model => model.correo, new { htmlAttributes = new { @class = "form-control", type = "email" } })
                @Html.ValidationMessageFor(model => model.correo, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />

        <div class="form-group row" style="text-align:right">
            @Html.LabelFor(model => model.telefono, htmlAttributes: new { @class = "control-label col-sm-2", @style = "padding-top:5px" })
            <div class="col-sm-10" style="text-align:left">
                @Html.EditorFor(model => model.telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.telefono, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />

        <div class="form-group row" style="text-align:right">
            @Html.LabelFor(model => model.fechaNacimiento, htmlAttributes: new { @class = "control-label col-sm-2", @style = "padding-top:5px" })
            <div class="col-sm-10" style="text-align:left">
                @Html.TextBoxFor(model => model.fechaNacimiento, "{0:yyyy-MM-dd}", new { @class = "form-control", type = "date" })
                @Html.ValidationMessageFor(model => model.fechaNacimiento, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />

        <div class="form-group row" style="text-align:right">
            @Html.LabelFor(model => model.curp, htmlAttributes: new { @class = "control-label col-sm-2", @style = "padding-top:5px" })
            <div class="col-sm-10" style="text-align:left">
                @Html.EditorFor(model => model.curp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.curp, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />

        <div class="form-group row" style="text-align:right">
            @Html.LabelFor(model => model.sueldo, htmlAttributes: new { @class = "control-label col-sm-2", @style = "padding-top:5px" })
            <div class="col-sm-10" style="text-align:left">
                @Html.EditorFor(model => model.sueldo, new { htmlAttributes = new { @class = "form-control", type = "number" } })
                @Html.ValidationMessageFor(model => model.sueldo, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />

        <div class="form-group row" style="text-align:right">
            @Html.LabelFor(model => model.idEstadoOrigen, htmlAttributes: new { @class = "control-label col-sm-2", @style = "padding-top:5px" })
            <div class="col-sm-10" style="text-align:left">
                @Html.DropDownList("idEstadoOrigen", new SelectList(ViewBag.listEstados, "id", "nombre"), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idEstadoOrigen, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />

        <div class="form-group row" style="text-align:right">
            @Html.LabelFor(model => model.idEstatus, htmlAttributes: new { @class = "control-label col-sm-2", @style = "padding-top:5px" })
            <div class="col-sm-10" style="text-align:left">
                @Html.DropDownList("idEstatus", new SelectList(ViewBag.listEstatus, "id", "nombre"), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idEstatus, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-2" style="text-align:right">
                <input type="submit" value="Actualizar" class="btn btn-success" />

            </div>
            <div class="col-auto">
                @Html.ActionLink("Regresar", "Index", null, new { @class = "btn btn-primary" })
            </div>

        </div>
    </div>
}




    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

C#/MVCEF3Capas/Presentacion/Views/Alumnos/Index.cshtml
@model IEnumerable<Entidades.Alumnos>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>
<h4>Alumnos</h4>
<hr />
@Html.ActionLink("Agregar", "Create", null, new { @class = "btn btn-primary" })
<br />
<br />
<table class="table table-dark" style="font-size:11px;">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.primerApellido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.segundoApellido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.correo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.telefono)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fechaNacimiento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.curp)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.sueldo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estados.nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EstatusAlumnos.nombre)
        </th>
        <th></th>
        <th></th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.primerApellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.segundoApellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.correo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.telefono)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.fechaNacimiento).ToString().Substring(1, 10)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.curp)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.sueldo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estados.nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EstatusAlumnos.nombre)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.id }, new { @class = "btn btn-success btn-sm" })
            </td>
            <td>
                @Html.ActionLink("Detalles", "Details", new { id = item.id }, new { @class = "btn btn-warning  btn-sm" })
            </td>
            <td>
                @Html.ActionLink("Eliminar", "Delete", new { id = item.id }, new { @class = "btn btn-danger  btn-sm" })
            </td>
        </tr>
    }

</table>

C#/MVCEF3Capas/Presentacion/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>